# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.22.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.22.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/nyholku/jCAE/occjava3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/nyholku/jCAE/occjava3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.22.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.22.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nyholku/jCAE/occjava3/CMakeFiles /Users/nyholku/jCAE/occjava3//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nyholku/jCAE/occjava3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OccJava

# Build rule for target.
OccJava: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OccJava
.PHONY : OccJava

# fast build rule for target.
OccJava/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OccJava.dir/build.make CMakeFiles/OccJava.dir/build
.PHONY : OccJava/fast

#=============================================================================
# Target rules for targets named OccJava_swig_compilation

# Build rule for target.
OccJava_swig_compilation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OccJava_swig_compilation
.PHONY : OccJava_swig_compilation

# fast build rule for target.
OccJava_swig_compilation/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OccJava_swig_compilation.dir/build.make CMakeFiles/OccJava_swig_compilation.dir/build
.PHONY : OccJava_swig_compilation/fast

src-java/org/jcae/opencascade/jni/OccJavaJAVA_wrap.o: src-java/org/jcae/opencascade/jni/OccJavaJAVA_wrap.cxx.o
.PHONY : src-java/org/jcae/opencascade/jni/OccJavaJAVA_wrap.o

# target to build an object file
src-java/org/jcae/opencascade/jni/OccJavaJAVA_wrap.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OccJava.dir/build.make CMakeFiles/OccJava.dir/src-java/org/jcae/opencascade/jni/OccJavaJAVA_wrap.cxx.o
.PHONY : src-java/org/jcae/opencascade/jni/OccJavaJAVA_wrap.cxx.o

src-java/org/jcae/opencascade/jni/OccJavaJAVA_wrap.i: src-java/org/jcae/opencascade/jni/OccJavaJAVA_wrap.cxx.i
.PHONY : src-java/org/jcae/opencascade/jni/OccJavaJAVA_wrap.i

# target to preprocess a source file
src-java/org/jcae/opencascade/jni/OccJavaJAVA_wrap.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OccJava.dir/build.make CMakeFiles/OccJava.dir/src-java/org/jcae/opencascade/jni/OccJavaJAVA_wrap.cxx.i
.PHONY : src-java/org/jcae/opencascade/jni/OccJavaJAVA_wrap.cxx.i

src-java/org/jcae/opencascade/jni/OccJavaJAVA_wrap.s: src-java/org/jcae/opencascade/jni/OccJavaJAVA_wrap.cxx.s
.PHONY : src-java/org/jcae/opencascade/jni/OccJavaJAVA_wrap.s

# target to generate assembly for a file
src-java/org/jcae/opencascade/jni/OccJavaJAVA_wrap.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OccJava.dir/build.make CMakeFiles/OccJava.dir/src-java/org/jcae/opencascade/jni/OccJavaJAVA_wrap.cxx.s
.PHONY : src-java/org/jcae/opencascade/jni/OccJavaJAVA_wrap.cxx.s

src/jnistream.o: src/jnistream.cxx.o
.PHONY : src/jnistream.o

# target to build an object file
src/jnistream.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OccJava.dir/build.make CMakeFiles/OccJava.dir/src/jnistream.cxx.o
.PHONY : src/jnistream.cxx.o

src/jnistream.i: src/jnistream.cxx.i
.PHONY : src/jnistream.i

# target to preprocess a source file
src/jnistream.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OccJava.dir/build.make CMakeFiles/OccJava.dir/src/jnistream.cxx.i
.PHONY : src/jnistream.cxx.i

src/jnistream.s: src/jnistream.cxx.s
.PHONY : src/jnistream.s

# target to generate assembly for a file
src/jnistream.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OccJava.dir/build.make CMakeFiles/OccJava.dir/src/jnistream.cxx.s
.PHONY : src/jnistream.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... OccJava_swig_compilation"
	@echo "... OccJava"
	@echo "... src-java/org/jcae/opencascade/jni/OccJavaJAVA_wrap.o"
	@echo "... src-java/org/jcae/opencascade/jni/OccJavaJAVA_wrap.i"
	@echo "... src-java/org/jcae/opencascade/jni/OccJavaJAVA_wrap.s"
	@echo "... src/jnistream.o"
	@echo "... src/jnistream.i"
	@echo "... src/jnistream.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

